In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\ASHWARY MAN\OneDrive\Desktop\survey.csv")
df.head(5)

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

In [3]:
df.drop(["Timestamp", "comments", "state"], axis=1, inplace=True)
df.head(5)

,Age,Gender,Country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,Female,United States,NaN,No,Yes,Often,6-25,No,Yes,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,44,M,United States,NaN,No,No,Rarely,More than 1000,No,No,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,32,Male,Canada,NaN,No,No,Rarely,6-25,No,Yes,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,31,Male,United Kingdom,NaN,Yes,Yes,Often,26-100,No,Yes,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,31,Male,United States,NaN,No,No,Never,100-500,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No

In [4]:
df = df[(df['Age'] >= 18) & (df['Age'] <= 70)]

In [5]:
df['Gender'] = df['Gender'].str.lower().str.strip()

In [6]:
male_terms = [
    'male','m','man','cis male','cis man','mail','make','mal','male-ish',
    'maile','msle','male (cis)','malr'
]

df['Gender'] = df['Gender'].replace(male_terms, 'male')

In [7]:
female_terms = [
    'female','f','woman','female ','cis female','cis-female/femme',
    'femake','femail','female (cis)'
]

df['Gender'] = df['Gender'].replace(female_terms, 'female')

In [8]:
df.loc[~df['Gender'].isin(['male','female']), 'Gender'] = 'other'

In [9]:
df.head(5)

,Age,Gender,Country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,female,United States,NaN,No,Yes,Often,6-25,No,Yes,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,44,male,United States,NaN,No,No,Rarely,More than 1000,No,No,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,32,male,Canada,NaN,No,No,Rarely,6-25,No,Yes,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,31,male,United Kingdom,NaN,Yes,Yes,Often,26-100,No,Yes,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,31,male,United States,NaN,No,No,Never,100-500,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No

In [10]:
df["Gender"].value_counts()

Gender
male      986
female    246
other      18
Name: count, dtype: int64

In [11]:
df.isnull().sum()

Age                            0
Gender                         0
Country                        0
self_employed                 18
family_history                 0
treatment                      0
work_interfere               262
no_employees                   0
remote_work                    0
tech_company                   0
benefits                       0
care_options                   0
wellness_program               0
seek_help                      0
anonymity                      0
leave                          0
mental_health_consequence      0
phys_health_consequence        0
coworkers                      0
supervisor                     0
mental_health_interview        0
phys_health_interview          0
mental_vs_physical             0
obs_consequence                0
dtype: int64

In [12]:
df.fillna("Unknown",inplace=True)

In [13]:
df.isnull().sum().sum()

0

In [14]:
x = df.drop("treatment",axis=1)
x.head(5)

,Age,Gender,Country,self_employed,family_history,work_interfere,no_employees,remote_work,tech_company,benefits,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,female,United States,Unknown,No,Often,6-25,No,Yes,Yes,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,44,male,United States,Unknown,No,Rarely,More than 1000,No,No,Don't know,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,32,male,Canada,Unknown,No,Rarely,6-25,No,Yes,No,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,31,male,United Kingdom,Unknown,Yes,Often,26-100,No,Yes,No,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,31,male,United States,Unknown,No,Never,100-500,Yes,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No

In [15]:
y = df["treatment"]
y.head(5)

0    Yes
1     No
2     No
3    Yes
4     No
Name: treatment, dtype: object

In [16]:
for i in x.columns:
    print(i,':','\n',x[i].unique(),'\n')

Age :
 [37 44 32 31 33 35 39 42 23 29 36 27 46 41 34 30 40 38 50 24 18 28 26 22
 19 25 45 21 43 56 60 54 55 48 20 57 58 47 62 51 65 49 53 61]

Gender :
 ['female' 'male' 'other']

Country :
 ['United States' 'Canada' 'United Kingdom' 'Bulgaria' 'France' 'Portugal'
 'Netherlands' 'Switzerland' 'Poland' 'Australia' 'Germany' 'Russia'
 'Mexico' 'Brazil' 'Slovenia' 'Costa Rica' 'Austria' 'Ireland' 'India'
 'South Africa' 'Italy' 'Sweden' 'Colombia' 'Latvia' 'Romania' 'Belgium'
 'New Zealand' 'Spain' 'Finland' 'Uruguay' 'Israel'
 'Bosnia and Herzegovina' 'Hungary' 'Singapore' 'Japan' 'Nigeria'
 'Croatia' 'Norway' 'Thailand' 'Denmark' 'Greece' 'Moldova' 'Georgia'
 'China' 'Czech Republic' 'Philippines']

self_employed :
 ['Unknown' 'Yes' 'No']

family_history :
 ['No' 'Yes']

work_interfere :
 ['Often' 'Rarely' 'Never' 'Sometimes' 'Unknown']

no_employees :
 ['6-25' 'More than 1000' '26-100' '100-500' '1-5' '500-1000']

remote_work :
 ['No' 'Yes']

tech_company :
 ['Yes' 'No']

benefits :
 ['Yes' "Don't know" 'No']

care_options :
 ['Not sure' 'No' 'Yes']

wellness_program :
 ['No' "Don't know" 'Yes']

seek_help :
 ['Yes' "Don't know" 'No']

anonymity :
 ['Yes' "Don't know" 'No']

leave :
 ['Somewhat easy' "Don't know" 'Somewhat difficult' 'Very difficult'
 'Very easy']

mental_health_consequence :
 ['No' 'Maybe' 'Yes']

phys_health_consequence :
 ['No' 'Yes' 'Maybe']

coworkers :
 ['Some of them' 'No' 'Yes']

supervisor :
 ['Yes' 'No' 'Some of them']

mental_health_interview :
 ['No' 'Yes' 'Maybe']

phys_health_interview :
 ['Maybe' 'No' 'Yes']

mental_vs_physical :
 ['Yes' "Don't know" 'No']

obs_consequence :
 ['No' 'Yes']

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
le = LabelEncoder()
for col in x.columns:
    x[col] = le.fit_transform(x[col])

In [19]:
x.head(10)

,Age,Gender,Country,self_employed,family_history,work_interfere,no_employees,remote_work,tech_company,benefits,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,19,0,44,1,0,1,4,0,1,2,...,2,2,1,1,1,2,1,0,2,0
1,26,1,44,1,0,2,5,0,0,0,...,0,0,0,1,0,0,1,1,0,0
2,14,1,6,1,0,2,4,0,1,1,...,0,1,1,1,2,2,2,2,1,0
3,13,1,43,1,1,1,2,0,1,1,...,1,1,2,2,1,0,0,0,1,1
4,13,1,44,1,0,0,1,1,1,2,...,0,0,1,1,1,2,2,2,0,0
5,15,1,44,1,1,3,4,0,1,2,...,0,0,1,1,2,2,1,0,0,0
6,17,0,44,1,1,3,0,1,1,1,...,1,1,0,0,1,0,1,1,0,0
7,21,1,6,1,0,0,0,1,1,1,...,2,0,1,1,0,0,1,1,1,0
8,24,0,44,1,1,3,1,0,1,2,...,1,3,0,1,2,2,1,0,1,0
9,5,1,6,1,0,0,2,0,1,0,...,0,0,1,1,2,2,0,0,2,0

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix